plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: pconrad/ucsb-cs-jekyll-theme-try2

url: https://ucsb-cs111.github.io # the base hostname & protocol for your site
baseurl: "/w19"  # the subpath of your site, e.g. "/blog"

course: "CS111"
course_title: "Introduction to Computational Science"
title: "UCSB CS111 W19"
github_url: https://github.com/ucsb-cs111/w19
qtr: "W19"
quarter: "Winter 2019"


kramdown:
   parse_block_html: false



exclude:
  - 'vendor'
  - 'setup.sh'
  - 'jekyll.sh'
include:
  - '_pages'


  
timezone: America/Los_Angeles

collections:
  info:
    output: true
    permalink: /info/:path/


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: pages
    values:
      layout: "default"

  - scope:
      path: ""
      type: info
    values:
      layout: default

  - scope:
      path: ""
      type: resources
    values:
      layout: default


